#!/usr/bin/env python3
from flask import Blueprint, jsonify

bp = Blueprint("health", __name__, url_prefix="/health"

@bp.get("")
def health():
    """
    Health check endpoint
    ---
    tags:
      - System
    responses:
      200:
        description: API is healthy
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: ok
    """
    return jsonify({"status": "ok"}), 200
